# Generated by Django 2.1.3 on 2018-11-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='coursename', max_length=200),
            preserve_default=False,
        ),
    ]
